import Head from 'next/head'
import Image from 'next/image'
import React, { useState } from 'react'

import { Navbar } from '../../components/Navbar'
import { HowCard } from '../../components/HowCard'
import { Footer } from '../../components/Footer'
import { HeroCard } from '../../components/HeroCard'
import styles from './index.module.css'
import { Options } from '../../components/Options'
import { questions } from './questions'

const Subscribe = () => {
	const [options, setOptions] = useState({
		question_1: 'Filter',
		question_2: 'Decaf',
		question_3: '250g',
		question_4: 'Cafatiere',
		question_5: 'Every Week',
	})

	return (
		<div className=''>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className='page-container'>
				{/* HEADER */}
				<Navbar></Navbar>

				{/* HERO */}
				<HeroCard
					title='Create a plan'
					description='Build a subscription plan that best fits your needs. We offer an assortment of the best 
          artisan coffees from around the globe delivered fresh to your door.'
					bgURL='/assets/plan/mobile/image-hero-blackcup.jpg'
				></HeroCard>

				{/* Instructions */}
				<div className={styles.instructions_container}>
					<HowCard
						title='Pick your coffee'
						description='Select from our evolving range of artisan coffees. Our beans are ethically
						sourced and we pay fair prices for them. There are new coffees in all profiles
						every month for you to try out.'
						number='01'
					/>
					<HowCard
						title='Choose the frequency'
						description='Customize your order frequency, quantity, even your roast style and grind type.
						Pause, skip or cancel your subscription with no commitment through our online portal.'
						number='02'
					/>
					<HowCard
						title='Receive and enjoy!'
						description='We ship your package within 48 hours, freshly roasted. Sit back and enjoy award-winning
						world-class coffees curated to provide a distinct tasting experience.'
						number='03'
					/>
				</div>

				{/* OPTIONS */}
				<Options question='How do you drink your coffee?' options={questions[0]}></Options>
				<Options question='What type of coffee?' options={questions[1]}></Options>
				<Options question='How much would you like?' options={questions[2]}></Options>
				<Options question='Want us to grind them?' options={questions[3]}></Options>
				<Options question='How often should we deliver?' options={questions[4]}></Options>

				{/* SUMMARY */}
				<div className={styles.createplan_container}>
					<div className={styles.summary_container}>
						<h2>Order Summary</h2>
						<p>
							“I drink coffee <span className={styles.textHighlight}>{options.question_1}</span>,
							with a <span className={styles.textHighlight}>{options.question_2}</span> type of
							bean. <span className={styles.textHighlight}>{options.question_3}</span> ground ala{' '}
							<span className={styles.textHighlight}>{options.question_4}</span>, sent to me{' '}
							<span className={styles.textHighlight}>{options.question_5}</span>.”
						</p>
					</div>

					<button className='button-primary'>Create my plan!</button>
				</div>
				<Footer></Footer>
			</main>
		</div>
	)
}
export default Subscribe
